# Generated by Django 3.0.6 on 2020-05-19 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='bottle_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date bottled'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='brew_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date brewed'),
        ),
    ]
